version: '3.8'

services:
  scaleway:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn pur_beurre.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/pur_beurre/scaleway/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/pur_beurre/scaleway/staticfiles
    ports:
      - 1337:80
    depends_on:
      - scaleway

volumes:
  postgres_data:
  static_volume: