FROM alpine:3.3

RUN apk add --no-cache tree
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python

ADD crontab.txt /crontab.txt
ADD script.sh /script.sh
COPY entry.sh /entry.sh
RUN chmod 755 /script.sh /entry.sh
RUN /usr/bin/crontab /crontab.txt

CMD ["/entry.sh"]